Organized VC Contents and Added Documentation
cuappdev/scoop-ios pull request #62
Opened 2023-09-15 17:54 UTC by rs929

## Overview

Organized and Annotated All VCs
Added Documentation to functions

2023-09-15 19:15 UTC, vinnie4k requested changes
Looks good! Just make sure you keep things consistent (i.e. line below for every `// MARK`). I know you just moved everything around, but next time document the files that you moved in the PR. Once you address these comments (make sure to mark them as resolved), request me again.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Home/HomeViewController.swift
> +    // MARK: - Identifers
Identifiers

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Home/NotificationsViewController.swift
> +// MARK: - UITableViewDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Home/NotificationsViewController.swift
> +// MARK: - UITableViewDataSource
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/LocationViewController.swift
> +// MARK: - GMSAutocompleteTableDataSourceDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/MatchesViewController.swift
> +// MARK: - UITableViewDataSource
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/MatchesViewController.swift
> +// MARK: - UITableViewDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/FavoritesViewController.swift
> +// MARK: - UITextFieldDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/OnboardingContainerViewController.swift
> +// MARK: - AnimationDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/OnboardingContainerViewController.swift
> +    // MARK: - Views
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/OnboardingViewController.swift
> +    // MARK: - Views
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/OnboardingViewController.swift
> +    // MARK: - Lifecycle Functions
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/PreferencesViewController.swift
> +    // MARK: - Views
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/PreferredContactViewController.swift
> +// MARK: - UITextFieldDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/ProfilePictureViewController.swift
> +// MARK: - UIImagePickerControllerDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Onboarding/VerifyPhoneNumberViewController.swift
> +// MARK: - UITextFieldDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Ride Posting/InitialPostRideViewController.swift
> +// MARK: - SearchInitialViewControllerDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Ride Posting/PostRideContainerViewController.swift
> +// MARK: - AnimationDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Ride Posting/PostRidePageViewController.swift
> +// MARK: - UIPageViewControllerDataSource
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Ride Posting/PostRidePageViewController.swift
> +// MARK: - OnboardingDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Ride Posting/PostRideSummaryViewController.swift
> +// MARK: - PostRideDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Ride Posting/PostRideTripDetailsViewController.swift
> +
Remove this line

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Ride Posting/PostRideTripDetailsViewController.swift
> +// MARK: - UITextFieldDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/Controller/Ride Posting/PostRideTripDetailsViewController.swift
> +// MARK: - UITextViewDelegate
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/SearchRidesViewController.swift
> +    // MARK: - Data
Keep it consistent and add a new line below.

2023-09-15 19:15 UTC, vinnie4k commented on Scoop/SearchRidesViewController.swift
> +    // MARK: - Lifecycle Functions
Keep it consistent and add a new line below.

2023-09-16 22:48 UTC, vinnie4k approved these changes
Good to go! Next time add more information about what you moved around in the PR for documentation purposes, and also mark the comments as "Resolved" when you resolve them.

2023-09-17 15:32 UTC, tiffany-pann commented on Scoop/Controller/Onboarding/VerifyPhoneNumberViewController.swift
>      func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
Line break here

2023-09-17 15:43 UTC, tiffany-pann approved these changes
LGTM! Fun PR to read 🚀

2023-09-18 19:06 UTC, merged