Added gradient hover view with save/cancel buttons in EditProfileVC
cuappdev/scoop-ios pull request #69
Opened 2023-10-18 19:52 UTC by caitlynjin

## Overview

Added a gradient hover view along with buttons to cancel or save the changed data fields in `EditProfileViewController` to the database and `ProfileViewController`. Created delete account button inside the scroll view (not yet functional).

## Changes Made

### Edit Profile Page

- Created a cancel button that simply pops the view controller and a save button that updates the user data and in `ProfileViewController` based on input information from the page.
  - Save button has the same implementation as `viewWillDisappear`, which was previously used to save the user data.
  - Removed `viewWillDisappear`.
- Created a white gradient that fades to transparent, which sticks to the screen (not scrollable) underneath the buttons.
  - Made user unable to interact with `gradientView`, so the user will be able to scroll underneath the gradient.
- Changed constraints regarding hiding/unhiding `phoneNumTextField` because the gradient would overlap with the view. The screen updates according to the button selection.
- Created the UI for the delete account button.

### Minor Changes

- Made back button and navigation bar hidden in pushed instance of `EditProfileViewController`.
- Added fonts in `Extension+UIFont.swift`. Changed SF Pro fonts to `.systemFont`.
- Reorganized and added colors in `Extension+UIColor.swift`.

## Test Coverage

- Did manual testing through simulator to ensure view constraints after button selection is implemented correctly.

## Next Steps

- Create networking request for deleting a user account and call the request when selecting the delete button (add confirmation message?).
- Double check save/cancel button after our backend is working.

## Screenshots

<details>

  <summary>Before</summary>

  https://github.com/cuappdev/scoop-ios/assets/118781810/4a3e0f8f-450c-4cf8-95a5-1dfb2d96b4d9

</details>

<details>

  <summary>After</summary>

  https://github.com/cuappdev/scoop-ios/assets/118781810/a017e7e8-d9a5-4e57-bf3e-4389279d9499

</details>

2023-10-18 20:03 UTC, vinnie4k requested changes
Great work! Just one think you might want to double check, usually you can dismiss a ViewController by swiping from the side. Since there is no longer a back button, I would double check that this feature is disabled. The only way to dismiss the view would either be to save or to cancel.

Please address my comments then request me again.

2023-10-18 20:03 UTC, vinnie4k commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +                view.layoutIfNeeded()
You can move this outside of the if statement since it is being used in both cases.

2023-10-18 20:03 UTC, vinnie4k commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +        gradientLayer.colors = [UIColor.white.withAlphaComponent(0).cgColor, UIColor.white.withAlphaComponent(0.3).cgColor, UIColor.white.withAlphaComponent(0.6).cgColor, UIColor.white.withAlphaCompo
This is difficult to read. Whenever you have an array with many values, separate each element with a new line.

2023-10-18 20:03 UTC, vinnie4k commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +    }
If these are not being called anywhere else, mark them as `private`.

2023-10-18 20:03 UTC, vinnie4k commented on Scoop/Supporting/Utilities/Extension+UIColor.swift
> +    static let textFieldBorderColor = UIColor(red: 106/255, green: 115/255, blue: 125/255, alpha: 1)
Nice.

2023-10-18 20:03 UTC, vinnie4k commented on Scoop/Supporting/Utilities/Extension+UIFont.swift
> +    static let bodySemibold = UIFont.systemFont(ofSize: 16, weight: .semibold)
Really nice. Using extensions is very powerful.

2023-10-18 20:11 UTC, caitlynjin commented
> Great work! I really like the PR description. Just one think you might want to double check, usually you can dismiss a ViewController by swiping from the side. Since there is no longer a back button, I would double check that this feature is disabled. The only way to dismiss the view would either be to save or to cancel.
> 
> Please address my comments then request me again.

It looks like it's already disabled 👍

2023-10-18 21:40 UTC, rs929 approved these changes
Looks good to me! Just a few minor changes. Whenever there are any constraints that are odd or not a multiple of 4, just round or truncate to keep things consistent.

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/LoginViewController.swift
> +//            self.signIn()
Uncomment this, since this is only temporary while the backend is down

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.height.equalTo(51)
I would just make this 50 to keep it even

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.height.equalTo(201)
Same as above, make this 200

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +        gradientLayer.colors = [
Maybe add this to the UIColor Extension, in case we need to utilize the same type of gradient again

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +        cancelButton.layer.cornerRadius = 24
Make this 25 to keep it consistent with other buttons

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.height.equalTo(51)
Make this 50

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +        saveButton.layer.cornerRadius = 24
Same as above

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.height.equalTo(51)
Same as above

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.bottom.equalTo(view.safeAreaLayoutGuide.snp.bottom).inset(39)
Make this 40

2023-10-18 21:40 UTC, rs929 commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.bottom.equalTo(view.safeAreaLayoutGuide.snp.bottom).inset(39)
Make this 40

2023-10-18 21:56 UTC, tiffany-pann requested changes
Nice PR! Feel free to re-request after the small constants issue. From your screen-recording, I noticed that the buttons felt a little too high up, not sure if this was based on design (but if it is, ignore me). 

Also, this is something else really small, but from the "Before" screen recording, I noticed that the phone number text-field still has its cursor (little vertical bar) flashing even after you're finished inputting and moved on to interacting with the sliders. This shouldn't be too bad, I think you could just add something like: 
`func textFieldDidEndEditing(_ textField: UITextField) {
        textField.tintColor = .clear
    }
`
No worries about this tho, just something small I noticed! Great work so far ( •̀ ω •́ )✧

2023-10-18 21:56 UTC, tiffany-pann commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            UIColor.white.cgColor,
so much white ⬜️🤍

2023-10-18 21:56 UTC, tiffany-pann commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.width.equalTo(102)
Same thing as prev. concern about this being a constant

2023-10-18 21:56 UTC, tiffany-pann commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.height.equalTo(51)
Similarly, same thing as previous comment

2023-10-18 21:56 UTC, tiffany-pann commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.width.equalTo(102)
Same concern about this being a constant & its height constraint as well

2023-10-18 21:56 UTC, tiffany-pann commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            make.height.equalTo(51)
Hmm does this look okay for smaller screens? i.e. iPhone SE lol. If np, feel free to disregard my following comments

2023-10-18 21:58 UTC, caitlynjin commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +            UIColor.white.cgColor,
indeed 🤍

2023-10-19 05:43 UTC, vinnie4k approved these changes
Address my comments and you should be good to go!

2023-10-19 05:43 UTC, vinnie4k commented on Scoop/Controller/Profile/EditProfileViewController.swift
>      private let textFieldHeight = 56
If this style is used in other places throughout the codebase then it's fine. However, I like to convert it to the following:
```suggestion
    private struct Constants {
        static let bottomInset: CGFloat = 36
        static let buttonCornerRadius: CGFloat = CGFloat(25)
        static let buttonHeight: CGFloat = 50
        static let buttonLeadingTrailingInset: CGFloat = 24
        static let buttonWidth: CGFloat = 104
        static let leadingTrailingInset: CGFloat = 32
        static let textFieldHeight: CGFloat = 56
    }
```
You would then call it using `Constants.bottomInset`

2023-10-19 05:43 UTC, vinnie4k commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +    func dismissKeyboardFromTap() {
Is this being called anywhere else? Mark this as `private` if so.

2023-10-19 05:43 UTC, vinnie4k commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +    func dismissKeyboardFromPan() {
Is this being called anywhere else? Mark this as `private` if so.

2023-10-19 05:43 UTC, vinnie4k commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +        let pan: UIPanGestureRecognizer = UIPanGestureRecognizer(target: self, action: #selector(dismissKeyboardTouchOutside))
```suggestion
        let pan = UIPanGestureRecognizer(target: self, action: #selector(dismissKeyboardTouchOutside))
```

2023-10-19 05:43 UTC, vinnie4k commented on Scoop/Controller/Profile/EditProfileViewController.swift
> +        let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboardTouchOutside))
```suggestion
        let tap = UITapGestureRecognizer(target: self, action: #selector(dismissKeyboardTouchOutside))
```

2023-10-19 06:13 UTC, caitlynjin commented
> Nice PR! Feel free to re-request after the small constants issue. From your screen-recording, I noticed that the buttons felt a little too high up, not sure if this was based on design (but if it is, ignore me).
> 
> Also, this is something else really small, but from the "Before" screen recording, I noticed that the phone number text-field still has its cursor (little vertical bar) flashing even after you're finished inputting and moved on to interacting with the sliders. This shouldn't be too bad, I think you could just add something like: `func textFieldDidEndEditing(_ textField: UITextField) { textField.tintColor = .clear } ` No worries about this tho, just something small I noticed! Great work so far ( •̀ ω •́ )✧

I tried the textFieldDidEndEditing, but I changed it to dismissing the keyboard for just the sliders because the keyboard doesn't need to be displayed for them. I made an updated video in the PR!

2023-10-21 19:00 UTC, tiffany-pann approved these changes

2023-10-21 19:04 UTC, merged